services:
  iot-app:
    image: iot-cli:latest
    restart: always
    command: --host 0.0.0.0:8080 --broker mqtt://158.23.162.90
    environment:
      DATABASE_URL: mysql://root@host.docker.internal/iot
      RUST_LOG: info
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "-X", "POST", "http://localhost:8080/ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
